services:
  keyserver-redis:
    image: redis:8.2
    container_name: keyserver_redis
    restart: unless-stopped
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--save 60 1"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "traefik.enable=false"

  keyserver-redis-r1:
    image: redis:8.2
    container_name: keyserver_redis_r1
    restart: unless-stopped
    command:
      - "redis-server"
      - "--replicaof keyserver-redis 6379"
      - "--replica-read-only yes"
      - "--appendonly yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - keyserver-redis
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "traefik.enable=false"

  keyserver-backend:
    image: harbor.rootcloud.ir/devops/keyserver-backend:latest
    restart: unless-stopped
    volumes:
      - "./site-packages:/usr/local/lib/python3.14/site-packages"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.keyserver-backend.rule=Host(`keyserver-backend.arsalanse.ir`)"
      - "traefik.http.routers.keyserver-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.keyserver-backend.entrypoints=http,https"
      - "traefik.http.services.keyserver-backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.keyserver-backend.observability.metrics=false"
      - "traefik.http.routers.keyserver-backend.observability.accessLogs=false"
      - "traefik.http.routers.keyserver-backend.observability.tracing=false"

  keyserver-frontend:
    image: harbor.rootcloud.ir/devops/keyserver-frontend:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.keyserver-frontend.rule=Host(`keyserver-frontend.arsalanse.ir`)"
      - "traefik.http.routers.keyserver-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.keyserver-frontend.entrypoints=http,https"
      - "traefik.http.services.keyserver-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.keyserver-frontend.observability.metrics=false"
      - "traefik.http.routers.keyserver-frontend.observability.accessLogs=false"
      - "traefik.http.routers.keyserver-frontend.observability.tracing=false"

networks:
  web:
    external: true
